[package]
name = "netconsd"
version = "0.1.0"
edition = "2021"
links="netconsd"

[[bin]]
name = "netconsd"
path = "main.rs"

[dependencies]
libc = "0.2.135"
clap = {version = "3.2.22", features = ["derive"] }
anyhow = "1.0.66"

[profile.release]
lto = true
strip = true
