[package]
name = "self_test_module"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.15.0"
libc = "0.2.40"
netconsd_module = {path = "../module"}
netconsblaster = {path = "../blaster"}
nix = {version = "0.25.0", features = ["signal", "process"]}

[lib]
crate-type = ["dylib"]
