[package]
name = "netconsblaster"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "netconsblaster"
path = "src/main.rs"

[lib]
name = "libblaster"
path = "src/lib.rs"

[dependencies]
libc = "0.2.40"
byteorder = "1.4.3"
clap = {version = "3.2.22", features = ["derive"] }
rand = "0.8.5"
